#ifndef HEADER_H
#define HEADER_H

#include "stm32f4xx_hal.h"

void HAL_TIM_MspPostInit(TIM_HandleTypeDef *htim);

void Error_Handler(void);

#define SERV_1_Pin GPIO_PIN_13
#define SERV_1_GPIO_Port GPIOC
#define SERV_2_Pin GPIO_PIN_13
#define SERV_2_GPIO_Port GPIOC
#define SERV_3_Pin GPIO_PIN_13
#define SERV_3_GPIO_Port GPIOC
#define SPI4_CS2_Pin GPIO_PIN_13
#define SPI4_CS2_GPIO_Port GPIOC
#define PT_CH_7_Pin GPIO_PIN_13
#define PT_CH_7_GPIO_Port GPIOC
#define PT_CH_6_Pin GPIO_PIN_13
#define PT_CH_6_GPIO_Port GPIOC
#define PT_CH_5_Pin GPIO_PIN_13
#define PT_CH_5_GPIO_Port GPIOC
#define PT_CH_4_Pin GPIO_PIN_13
#define PT_CH_4_GPIO_Port GPIOC
#define SCL_Pin GPIO_PIN_13
#define SCL_GPIO_Port GPIOC
#define SWDIO_Pin GPIO_PIN_13
#define SWDIO_GPIO_Port GPIOC
#define SWDCLK_Pin GPIO_PIN_13
#define SWDCLK_GPIO_Port GPIOC
#define PT_CH_1_Pin GPIO_PIN_13
#define PT_CH_1_GPIO_Port GPIOC
#define PT_CH_0_Pin GPIO_PIN_13
#define PT_CH_0_GPIO_Port GPIOC
#define QSPI_CLK_Pin GPIO_PIN_13
#define QSPI_CLK_GPIO_Port GPIOC
#define SPI1_SCK_Pin GPIO_PIN_13
#define SPI1_SCK_GPIO_Port GPIOC
#define SPI1_MISO_Pin GPIO_PIN_13
#define SPI1_MISO_GPIO_Port GPIOC
#define SPI1_MOSI_Pin GPIO_PIN_13
#define SPI1_MOSI_GPIO_Port GPIOC
#define PWM_1_Pin GPIO_PIN_13
#define PWM_1_GPIO_Port GPIOC
#define PWM_2_Pin GPIO_PIN_13
#define PWM_2_GPIO_Port GPIOC
#define PWM_3_Pin GPIO_PIN_13
#define PWM_3_GPIO_Port GPIOC
#define SPI4_CS1_Pin GPIO_PIN_13
#define SPI4_CS1_GPIO_Port GPIOC
#define SPI4_CS3_Pin GPIO_PIN_13
#define SPI4_CS3_GPIO_Port GPIOC
#define SPI4_SCK_Pin GPIO_PIN_13
#define SPI4_SCK_GPIO_Port GPIOC
#define SPI4_MISO_Pin GPIO_PIN_13
#define SPI4_MISO_GPIO_Port GPIOC
#define SPI4_MOSI_Pin GPIO_PIN_13
#define SPI4_MOSI_GPIO_Port GPIOC
#define SOL_0_Pin GPIO_PIN_13
#define SOL_0_GPIO_Port GPIOC
#define SOL_1_Pin GPIO_PIN_13
#define SOL_1_GPIO_Port GPIOC
#define SOL_2_Pin GPIO_PIN_13
#define SOL_2_GPIO_Port GPIOC
#define PT_CH_3_Pin GPIO_PIN_13
#define PT_CH_3_GPIO_Port GPIOC
#define PT_CH_2_Pin GPIO_PIN_13
#define PT_CH_2_GPIO_Port GPIOC
#define SPI1_CS0_Pin GPIO_PIN_13
#define SPI1_CS0_GPIO_Port GPIOC
#define SPI1_CS1_Pin GPIO_PIN_13
#define SPI1_CS1_GPIO_Port GPIOC
#define QSPI_NCS_Pin GPIO_PIN_13
#define QSPI_NCS_GPIO_Port GPIOC
#define WS2812_Pin GPIO_PIN_13
#define WS2812_GPIO_Port GPIOC
#define SOL_GPIO_2_Pin GPIO_PIN_13
#define SOL_GPIO_2_GPIO_Port GPIOC
#define SOL_GPIO_1_Pin GPIO_PIN_13
#define SOL_GPIO_1_GPIO_Port GPIOC
#define SOL_GPIO_0_Pin GPIO_PIN_13
#define SOL_GPIO_0_GPIO_Port GPIOC
#define PWRTR_Pin GPIO_PIN_13
#define PWRTR_GPIO_Port GPIOC
#define QSPI_IO_0_Pin GPIO_PIN_13
#define QSPI_IO_0_GPIO_Port GPIOC
#define QSPI_IO_1_Pin GPIO_PIN_13
#define QSPI_IO_1_GPIO_Port GPIOC
#define QSPI_IO_2_Pin GPIO_PIN_13
#define QSPI_IO_2_GPIO_Port GPIOC
#define QSPI_IO_3_Pin GPIO_PIN_13
#define QSPI_IO_3_GPIO_Port GPIOC
#define SPI4_SCK_Pin GPIO_PIN_13
#define SPI4_SCK_GPIO_Port GPIOC
#define SPI4_MISO_Pin GPIO_PIN_13
#define SPI4_MISO_GPIO_Port GPIOC
#define SPI4_MOSI_Pin GPIO_PIN_13
#define SPI4_MOSI_GPIO_Port GPIOC
#define SPI4_CS0_Pin GPIO_PIN_13
#define SPI4_CS0_GPIO_Port GPIOC
#define CAN_RX_Pin GPIO_PIN_13
#define CAN_RX_GPIO_Port GPIOC
#define CAN_TX_Pin GPIO_PIN_13
#define CAN_TX_GPIO_Port GPIOC
#define SERV_CTL_1_Pin GPIO_PIN_13
#define SERV_CTL_1_GPIO_Port GPIOC
#define SERV_CTL_2_Pin GPIO_PIN_13
#define SERV_CTL_2_GPIO_Port GPIOC
#define SERV_CTL_3_Pin GPIO_PIN_13
#define SERV_CTL_3_GPIO_Port GPIOC
#define SPI2_CS0_Pin GPIO_PIN_13
#define SPI2_CS0_Pin_GPIO_Port GPIOC
#define SCL_1_Pin GPIO_PIN_13
#define SCL_1_GPIO_Port GPIOC
#define SDA_1_Pin GPIO_PIN_13
#define SDA_1_GPIO_Port GPIOC

#endif // !HEADER_H